[build]
  publish = "static"

[functions]
  directory = "netlify/functions"

[functions.api]
  included_files = [
    "main.py",
    "data_loader.py",
    "vector_db.py",
    "custom_types.py"
  ]

[functions.inngest]
  included_files = [
    "main.py",
    "data_loader.py",
    "vector_db.py",
    "custom_types.py"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
